### ISSUE TITLE
Logout ExpressionError

### ISSUE THREAD

**Issue by Chriscxa** [DavideViolante/Angular-Full-Stack#165] opened 2018-02-12 23:50 UTC
First: Login,
Open Console,
And Logout!

Error:
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.

**Comment by DavideViolante** [comment] 2018-02-13 07:05
Duplicate of https://github.com/DavideViolante/Angular-Full-Stack/issues/105

**Closed by DavideViolante** 2018-02-13 07:05 UTC
