### ISSUE TITLE
Should we build docker images ?

### ISSUE THREAD

**Issue by Jackychans** [DavideViolante/Angular-Full-Stack#113] opened 2017-09-28 18:15 UTC
Not really an issue, just a suggestion if we plan to add Dockerfile to build docker images since docker's popularity getting increased over the time.

Thanks

**Comment by DavideViolante** [comment] 2017-09-28 19:40
Duplicate of https://github.com/DavideViolante/Angular-Full-Stack/issues/28 right?

**Closed by DavideViolante** 2017-09-28 19:40 UTC
